version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URI: mongodb://user:password@db:27017/protondb?authSource=admin
      PORT: 8080
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: